# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
eval_iter: 20        # How often do you want to save output images during training
display_size: 2               # How many images do you want to display each time
snapshot_save_iter: 20     # How often do you want to save trained models
gpuID: 0

# optimization options
max_iter: 100             # maximum number of training iterations
batch_size: 16                 # batch size
lr: 0.001                    # initial learning rate
weight_decay: 0.0001          # weight decay
beta1: 0.9                    # Adam parameter
beta2: 0.999                 # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]

# model options
activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
pad_type: reflect           # padding type [zero/reflect]
norm: none                  # normalization layer [none/bn/in/ln]

# data options
num_workers: 16                              # number of data loading threads
new_size: 64                             # first resize the shortest image side to this size
crop_image_height: 64                      # random crop image of this height
crop_image_width: 64                      # random crop image of this width

train_root: "C:/Users/sevda/PycharmProjects/Neural Network/HE/LOL_dataset/train_x"
val_root: "C:/Users/sevda/PycharmProjects/Neural Network/HE/LOL_dataset/test_x"
gt_root: "C:/Users/sevda/PycharmProjects/Neural Network/HE/LOL_dataset/test_gt"
# train_root: /content/drive/MyDrive/LOL_dataset/train_x
# val_root: /content/drive/MyDrive/LOL_dataset/test_x
# gt_root: /content/drive/MyDrive/LOL_dataset/test_gt